#include <iostream>
using namespace std;
//Produce correct size of various data types on your computer.
int main()
{
    cout << "Size of character : " << sizeof(char) << endl;
    cout << "Size of integer : " << sizeof(int) << endl;
    cout << "Size of short integer : " << sizeof(short int) << endl;
    cout << "Size of long integer : " << sizeof(long int) << endl;
    cout << "Size of float : " << sizeof(float) << endl;
    cout << "Size of double : " << sizeof(double) << endl;
    cout << "Size of wchar_t : " << sizeof(wchar_t) <<endl;

    return 0;

}
