#include<stdio.h>
#include<string.h>
int main()
{
    char x[]="BABABABABANANABABABABABANANABANANANAAHHPOTATONAAHAHBANANAAHAHTOGALINOPOTAHTONIGAHNIBAHLOBAHNIKAHNOJIGAHBABABABABANANAYOPLANOHULAPANONOTUMABANANALIKEANUPITALAMOOBANANABABABABANANABABABABABANANAPOTATOHOHOOOOOOTOGALINOPOTAHTONIGAHNIBAHLOBAHNIKAHNOJIGAHBABABABABANANAAAAAAAAADHISYAAAAAA" ;
    int i,l,c;
    l=strlen(x);
    c=0;
    for(i=0;i<l;i++)
    {
        if(x[i]=='A')
            c++;


    }
    printf("%d\n",c);
    return 0;
}
